### PR TITLE
CSL  Skin Update V?: I lost count edition

### PR DESCRIPTION
**Pull request by CSLeader**
-Added Dorito camo
-Added Mountain Dew camo
-Added MGS3 Banana Camo
-Added S.T.A.L.K.E.R. Monolith Camo
-Added Cat Corner camo
-Added two MEC camo variants

### CODE REVIEW

**Comment by Cuel** [comment]
dorito, mountain dew, what :-1:

**Comment by CSLeader** [comment]
But we must have it for the dank ebin.

**Comment by Cuel** [comment]
No, e.g the alicam uniform has only been used for "hah look at this", nothing more. It'll just take up space

**Comment by Mallow234** [comment]
Most of the skins are there for meme value and MEC skins already have better replacements - closed

**Pull request closed without merging**
