### PR TITLE
Added Monolith Camo and removes the useless config.cpp

### PR DESCRIPTION
**Pull request by litmeuplol**
Adds the Monolith camo from the STALKER series. Also deletes the pointless config.cpp file inside the main directory.
You can check an image of it ingame here - http://imgur.com/a/BG1gK
Please inform me if I fuck something up.

Credit to CSLeader for the icon and the idea.

### CODE REVIEW

**Comment by litmeuplol** [comment]
And I know there are 15 fucking commits, I'm stupid.

**Comment by Mallow234** [comment]
I didn't even know that config was there, thanks for spotting it!

**Comment by Tinter** [comment]
> Thanks for spotting
> Yeah good job on that one litmeuplol all by yourself.

**Comment by litmeuplol** [comment]
yeah it was tinter who noticed it after i edited it three fucking times
it was horrible

**Pull request merged**
